import uuid

from app.events.contracts import EventRule

EVENT_RULE_BUNDLE_VERSION = "e2-v1"
EVENT_DEFINITION_NAMESPACE = uuid.UUID("61c5d280-7ae7-4c87-a722-649077277f42")

RULES = (
    EventRule(
        code="THIRD_PARTY_DEPENDENCY_ADDED",
        family="DEPENDENCY",
        description="A third-party dependency appeared.",
        kind="POINT",
        default_severity="LOW",
        confirmation="SINGLE_STRONG_OBSERVATION",
        evidence_kinds=("CHECKPOINT_RUN", "ENTITY_OBSERVATION"),
        subject_kind="DOMAIN_ENTITY",
        diff_operator="PRESENCE_ADDED",
        aggregation_scope="EXACT_URL_SCENARIO",
        severity_policy="FIXED_DEFAULT",
        resolution_rule="NONE_POINT_EVENT",
        dedupe_strategy="SEMANTIC_TRANSITION",
        domain_refs=("F-BR-001",),
        noise_notes="Requires complete, non-truncated comparable dependency evidence.",
        rule_version="e1-v1",
    ),
    EventRule(
        code="THIRD_PARTY_DEPENDENCY_REMOVED",
        family="DEPENDENCY",
        description="A third-party dependency disappeared.",
        kind="POINT",
        default_severity="MEDIUM",
        confirmation="SINGLE_STRONG_OBSERVATION",
        evidence_kinds=("CHECKPOINT_RUN", "ENTITY_OBSERVATION"),
        subject_kind="DOMAIN_ENTITY",
        diff_operator="PRESENCE_REMOVED",
        aggregation_scope="EXACT_URL_SCENARIO",
        severity_policy="FIXED_DEFAULT",
        resolution_rule="NONE_POINT_EVENT",
        dedupe_strategy="SEMANTIC_TRANSITION",
        domain_refs=("F-BR-001",),
        noise_notes="Absence is invalid when either dependency set is truncated.",
        rule_version="e1-v1",
    ),
    EventRule(
        code="JS_ERROR_STARTED",
        family="JAVASCRIPT",
        description="A JavaScript error fingerprint appeared and persisted.",
        kind="CONDITION",
        default_severity="MEDIUM",
        confirmation="TWO_CONSECUTIVE_CHECKPOINTS",
        evidence_kinds=("CHECKPOINT_RUN", "JS_ERROR_OBSERVATION"),
        subject_kind="JS_ERROR_FINGERPRINT",
        diff_operator="CONDITION_PRESENT",
        aggregation_scope="EXACT_URL_SCENARIO",
        severity_policy="FIXED_DEFAULT",
        resolution_rule="ONE_COMPARABLE_CLEAN_CHECKPOINT",
        dedupe_strategy="ACTIVE_CONDITION_KEY",
        domain_refs=("F-BR-002",),
        noise_notes="One occurrence is noisy and remains pending.",
        rule_version="e2-v1",
    ),
    EventRule(
        code="NOINDEX_ADDED",
        family="SEO",
        description="A rendered noindex directive appeared.",
        kind="POINT",
        default_severity="MEDIUM",
        confirmation="SINGLE_STRONG_OBSERVATION",
        evidence_kinds=("CHECKPOINT_RUN", "SEO_OBSERVATION"),
        subject_kind="RENDERED_PAGE_OR_TEMPLATE",
        diff_operator="NOINDEX_ADDED",
        aggregation_scope="EXACT_URL_OR_TEMPLATE_SCENARIO",
        severity_policy="NOINDEX_SCOPE",
        resolution_rule="NONE_POINT_EVENT",
        dedupe_strategy="SEMANTIC_TRANSITION_OR_WINDOW_AGGREGATE",
        domain_refs=("F-SEO-002", "F-SEO-003"),
        noise_notes="One URL never implies template or site scope.",
        rule_version="e2-v1",
        min_valid_urls=2,
        min_affected_urls=2,
        critical_min_affected_urls=2,
    ),
    EventRule(
        code="CANONICAL_CHANGED",
        family="SEO",
        description="The rendered canonical URL changed.",
        kind="POINT",
        default_severity="MEDIUM",
        confirmation="SINGLE_STRONG_OBSERVATION",
        evidence_kinds=("CHECKPOINT_RUN", "SEO_OBSERVATION"),
        subject_kind="RENDERED_PAGE",
        diff_operator="VALUE_CHANGED",
        aggregation_scope="EXACT_URL_SCENARIO",
        severity_policy="FIXED_DEFAULT",
        resolution_rule="NONE_POINT_EVENT",
        dedupe_strategy="SEMANTIC_TRANSITION",
        domain_refs=("F-SEO-003",),
        noise_notes="Requires compatible rendered SEO observers.",
        rule_version="e1-v1",
    ),
    EventRule(
        code="GPT_EXPECTED_SLOT_MISSING",
        family="GPT",
        description="An expected GPT slot was not observed across representative URLs.",
        kind="CONDITION",
        default_severity="HIGH",
        confirmation="MULTI_URL_CORROBORATION",
        evidence_kinds=("CHECKPOINT_RUN", "GPT_SLOT_OBSERVATION"),
        subject_kind="GPT_SLOT_ENTITY",
        diff_operator="EXPECTED_PRESENCE_MISSING",
        aggregation_scope="TEMPLATE_SCENARIO",
        severity_policy="AFFECTED_URL_COUNT",
        resolution_rule="MULTI_URL_HEALTHY_CORROBORATION",
        dedupe_strategy="ACTIVE_CONDITION_KEY",
        domain_refs=("F-GPT-001",),
        noise_notes="One rotating representative URL cannot promote a template condition.",
        rule_version="e2-v1",
        min_valid_urls=2,
        min_affected_urls=2,
        critical_min_affected_urls=3,
    ),
)
RULES_BY_CODE = {rule.code: rule for rule in RULES}


def definition_id(code: str) -> uuid.UUID:
    if code not in RULES_BY_CODE:
        raise KeyError(code)
    return uuid.uuid5(EVENT_DEFINITION_NAMESPACE, code)
